# Generated by Django 2.1.7 on 2019-03-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='unid',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
