# Generated by Django 2.1.7 on 2019-03-14 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_details_unid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='unid',
        ),
    ]
